module.exports = {
    get_user:"/get",
    upload:"/upload",
    update_user:"/update",
    add_experience:"/add-experience",
    add_projects:"/add-projects",
    add_education:"/add-education",
    GetUser:"/get",
    api_auth:"/api/auth",
    api_user:"/api/user",
    api_list:"/api/list",
    storage:"/storage/*",
    register:"/register",
    login:"/login",
}